### ISSUE TITLE
Aggiunta prodotti in Portfolio Perfomance (da Finanzaonline)

### ISSUE THREAD

**Issue by 3Prosecco2Aperol1Soda** [enrichman/portfolio-performance#1]
Ciao, 
ti faccio l'elenco delle obbligazioni presenti nel portafoglio, ora non vorrei approfittare del tuo tempo e disponibiltà, per cui se ritieni eccessivo l'impegno non preocuparti e ti ringrazio comunque.

Sono tutti prodotti quotati su Borsa Italiana, segue elenco con nome prodotto e ISIN:

CITIGROUP 22/25 3.28         XS2110112971
MEDIOBANCA 3.4 22-26       XS2533094400
EIB 2.750% 23/28                  XS2587298204
ENI SPA 4.30% 23/28            IT0005521171
BRD 1% 2014/2024               DE0001102366
BTP-01DC32 2,50%               IT0005494239
AUSTRIA 2.90% 23-33           AT0000A324S8
BRD 1,5% 2014/2024             DE0001102358

Ti rinnovo i miei complimenti per quanto già fatto.
Saluti
NinnaNanna

**Comment by enrichman** [comment]
Ciao @3Prosecco2Aperol1Soda , grazie della issue. Ho provato al volo il primo e sembra tornare correttamente, devo aggiustare solo un paio di cose per poter gestire il mercato di riferimento.

Appena riesco a trovare un po' di tempo se sono su Borsa Italiana dovrei riuscire ad inserirli tutti!

**Comment by enrichman** [comment]
Ho colto l'occasione per riscrivere quasi totalmente l'applicazione. Ora integrare un nuovo fondo è alla portata di tutti, basta aggiungerlo al CSV, e se il loader è già implementato (tipo quello di Borsa Italiana) non è necessario fare altro. :smile: 

Trovi i dati nei link con l'ISIN, tipo: https://enrichman.github.io/portfolio-performance/json/XS2110112971.json

**Comment by 3Prosecco2Aperol1Soda** [comment]
Ciao, ho letto solo ora i messaggi a questa mail, mi sono fermato al forum e github !!!!    hai fatto un grande lavoro!        per aggiungere strumenti nuovi, ad esempio altre obbligazioni, và aggiunto al CSV.. puoi farmi capire come? su github?

    Il venerdì 21 luglio 2023 alle ore 16:59:47 CEST, Enrico Candino ***@***.***> ha scritto:  
 
 


Ho colto l'occasione per riscrivere quasi totalmente l'applicazione. Ora integrare un nuovo fondo è alla portata di tutti, basta aggiungerlo al CSV, e se il loader è già implementato (tipo quello di Borsa Italiana) non è necessario fare altro. 😄
 
Trovi i dati nei link con l'ISIN, tipo: https://enrichman.github.io/portfolio-performance/json/XS2110112971.json

**Comment by enrichman** [comment]
> Ciao, ho letto solo ora i messaggi a questa mail, mi sono fermato al forum e github !!!!    hai fatto un grande lavoro!        per aggiungere strumenti nuovi, ad esempio altre obbligazioni, và aggiunto al CSV.. puoi farmi capire come? su github?

Si, volendo puoi farlo direttamente su Github, modificando questo CSV: https://github.com/enrichman/portfolio-performance/blob/main/securities.csv e aprendo poi una _pull request_. 🙂

**Comment by 3Prosecco2Aperol1Soda** [comment]
..proverò a capire come fare, perchè naturalmente il CSV implementation è read only

    Il lunedì 24 luglio 2023 alle ore 17:45:25 CEST, Enrico Candino ***@***.***> ha scritto:  
 
 



Ciao, ho letto solo ora i messaggi a questa mail, mi sono fermato al forum e github !!!!    hai fatto un grande lavoro!        per aggiungere strumenti nuovi, ad esempio altre obbligazioni, và aggiunto al CSV.. puoi farmi capire come? su github?


Si, volendo puoi farlo direttamente su Github, modificando questo CSV: https://github.com/enrichman/portfolio-performance/blob/main/securities.csv e aprendo poi una pull request. 🙂
