### ISSUE TITLE
Reset out/json/DE000BU22007.json ed errore di scala

### ISSUE THREAD

**Issue by ilario-pierbattista** [enrichman/portfolio-performance#11]
Ciao :wave: 

con [questo commit](https://github.com/enrichman/portfolio-performance/commit/8db982df6a4929919edaebe66c025dfcec0d05f4) bot ha riscritto completamente DE000BU22007.json.

- log 5 marzo https://github.com/enrichman/portfolio-performance/actions/runs/8162457092/job/22313475542 <- riscrittura
- log 6 marzo https://github.com/enrichman/portfolio-performance/actions/runs/8194257265/job/22409870600

Il 5 marzo c'è stato un errore non sistematico di posizionamento della virgola. 

Non ho ancora controllato se sono i dati forniti da borsa italiana ad essere errati o meno.
Nel caso lo fossero, presumo non serva a nulla correggere il json a mano perchè bot lo riscriverebbe alla prossima esecuzione, corretto?

**Comment by enrichman** [comment]
Ciao @ilario-pierbattista, grazie per averlo notificato. Non ho ben idea di cosa sia successo ma credo qualche "glitch" da parte di Borsa Italiana. Vedendo i dati nel JSON ci sono valori precedenti alla data di emissione (02/02/23), che non ha molto senso.

I dati sbagliati sono rimasti lì perchè presi per "buoni". Ho provveduto a ricreare in toto il JSON, in modo da tornare ad avere dati puliti -> 33c47db042b5e5b9b6a1f921f5eb62a4e9bb8e0c

Chiudo! 😄
