### ISSUE TITLE
No cash account available

### ISSUE THREAD

**Issue by Cb2799** [enrichman/portfolio-performance#7]
hi all! i have an account with a bank that is not supported in the Deposit account tab. I can create the account but i can not upload any pdf file to that because that bank is not supported. How can i manage to add that bank so that i can attach a pdf file to that?

**Comment by enrichman** [comment]
Hi @Cb2799, unfortunately this repository is not the one of Portfolio Performance. You were probably looking for this one: https://github.com/portfolio-performance/portfolio

Closing. 🙂
